# Generated by Django 4.1.7 on 2023-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemana',
            name='nome',
            field=models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10),
        ),
    ]
