# Generated by Django 4.1.7 on 2023-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_diasemana_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemana',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
