# Generated by Django 4.1.7 on 2023-03-26 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=180)),
                ('nome_preferencia', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos numéricos')])),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero_residencia', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Senha deve conter no mínimo 8 caracteres'), django.core.validators.MaxLengthValidator(20, 'Senha deve conter no máximo 20 caracteres')], verbose_name='Senha')),
            ],
        ),
    ]
