# Generated by Django 4.1.7 on 2023-03-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contato',
            new_name='telefone',
        ),
    ]
